<?php

declare(strict_types=1);

return [
    'lock_guard_symbol' => 'RepositoryContractGuard::denyMixedSemanticsApi(',
    'runtime_method_suffixes' => [
        'InTenantScope',
        'InResolvedTenantScope',
        'InInvoicePlane',
    ],
    'non_runtime_method_markers' => [
        'ForRepair',
        'UnscopedForRepair',
        'ForControlPlane',
        'ForPlatform',
        'GlobalOps',
    ],
    'banned_generic_verbs' => [
        'find',
        'findForUpdate',
        'list',
        'count',
        'update',
        'softDelete',
        'delete',
        'lockWithDefinition',
        'lockWithDefinitionForBilling',
        'findByCode',
        'updateRepairOrUnscopedById',
    ],
    'runtime_sensitive_path_segments' => [
        '/controllers/',
        '/providers/',
        '/routes/',
        '/resources/',
    ],
    'runtime_sensitive_service_segment' => '/services/',
    'non_runtime_service_tokens' => [
        'Backfill',
        'Audit',
        'Retire',
        'Relink',
        'Finalization',
        'Drilldown',
        'Reconcile',
        'Recovery',
        'Snapshot',
        'Quality',
        'Readiness',
        'Cron',
        'Job',
        'Worker',
        'Smoke',
    ],
    'platform_surface_tokens' => [
        'Platform',
        'ControlPlane',
        'Founder',
        'Registry',
    ],
    'protected_repositories' => [
        [
            'class' => 'PackageRepository',
            'path' => 'packages/repositories/PackageRepository.php',
            'required_runtime_methods' => [
                'findInTenantScope',
                'listInTenantScope',
                'countInTenantScope',
                'updateInTenantScope',
                'softDeleteInTenantScope',
            ],
            'required_non_runtime_methods' => [],
            'locked_generic_methods' => ['find', 'list', 'count', 'update', 'softDelete'],
            'required_signals' => [
                "branchColumnOwnedByResolvedOrganizationExistsClause('p')",
                'findBranchOwnedPublicPurchasable',
            ],
        ],
        [
            'class' => 'ClientPackageRepository',
            'path' => 'packages/repositories/ClientPackageRepository.php',
            'required_runtime_methods' => [
                'findInTenantScope',
                'findForUpdateInTenantScope',
                'listInTenantScope',
                'countInTenantScope',
                'updateInTenantScope',
            ],
            'required_non_runtime_methods' => [],
            'locked_generic_methods' => ['find', 'findForUpdate', 'list', 'count', 'update'],
            'required_signals' => [
                "branchColumnOwnedByResolvedOrganizationExistsClause('cp')",
                'listEligibleForClientInTenantScope',
            ],
        ],
        [
            'class' => 'GiftCardRepository',
            'path' => 'gift-cards/repositories/GiftCardRepository.php',
            'required_runtime_methods' => [
                'findInTenantScope',
                'findLockedInTenantScope',
                'listInTenantScope',
                'countInTenantScope',
                'updateInTenantScope',
            ],
            'required_non_runtime_methods' => [
                'findByCodeForUniquenessCheck',
            ],
            'locked_generic_methods' => ['find', 'findByCode', 'list', 'count', 'update'],
            'required_signals' => [
                'giftCardVisibleFromBranchContextClause',
                'giftCardGlobalNullClientAnchoredInResolvedOrgClause',
            ],
        ],
        [
            'class' => 'ClientMembershipRepository',
            'path' => 'memberships/Repositories/ClientMembershipRepository.php',
            'required_runtime_methods' => [
                'findInTenantScope',
                'findInResolvedTenantScope',
                'findForUpdateInTenantScope',
                'findForUpdateInResolvedTenantScope',
                'lockWithDefinitionInTenantScope',
                'lockWithDefinitionInResolvedTenantScope',
                'lockWithDefinitionForBillingInTenantScope',
                'lockWithDefinitionForBillingInResolvedTenantScope',
                'updateInTenantScope',
            ],
            'required_non_runtime_methods' => [
                'findForRepair',
                'findForUpdateForRepair',
                'lockWithDefinitionForRepair',
                'lockWithDefinitionForBillingForRepair',
                'updateForRepairById',
                'listActiveNonExpiredForRenewalScanGlobalOps',
                'listExpiryTerminalCandidatesForGlobalCron',
            ],
            'locked_generic_methods' => [
                'find',
                'findForUpdate',
                'lockWithDefinition',
                'lockWithDefinitionForBilling',
                'updateRepairOrUnscopedById',
            ],
            'required_signals' => [
                'clientMembershipVisibleFromBranchContextClause',
                'getAnyLiveBranchIdForResolvedTenantOrganization',
            ],
        ],
        [
            'class' => 'MembershipSaleRepository',
            'path' => 'memberships/Repositories/MembershipSaleRepository.php',
            'required_runtime_methods' => [
                'findInTenantScope',
                'findInResolvedTenantScope',
                'findForUpdateInTenantScope',
                'findForUpdateInResolvedTenantScope',
                'updateInTenantScope',
                'updateInResolvedTenantScope',
                'listByInvoiceIdInInvoicePlane',
            ],
            'required_non_runtime_methods' => [
                'findForRepair',
                'findForUpdateForRepair',
                'updateForRepair',
                'listByInvoiceIdForRepair',
                'listDistinctInvoiceIdsForReconcile',
            ],
            'locked_generic_methods' => ['find', 'findForUpdate', 'update'],
            'locked_mixed_methods' => ['listByInvoiceId'],
            'required_signals' => [
                "branchColumnOwnedByResolvedOrganizationExistsClause('ms')",
                'strictTenantInvoicePlaneBranchScope',
                'resolvedOrganizationRepairInvoicePlaneBranchScopeIfAvailable',
                'isBranchOwnedTenantRuntimeBranchId',
            ],
        ],
        [
            'class' => 'MembershipBillingCycleRepository',
            'path' => 'memberships/Repositories/MembershipBillingCycleRepository.php',
            'required_runtime_methods' => [
                'findInInvoicePlane',
                'findForUpdateInInvoicePlane',
                'findForInvoiceInInvoicePlane',
                'findForUpdateForInvoiceInInvoicePlane',
                'listByInvoiceIdInInvoicePlane',
                'updateInInvoicePlane',
                'maxInvoicedCycleIdForMembershipInTenantScope',
                'maxInvoicedCycleIdForMembershipInResolvedTenantScope',
            ],
            'required_non_runtime_methods' => [
                'findForRepair',
                'findForUpdateForRepair',
                'findForInvoiceForRepair',
                'findForUpdateForInvoiceForRepair',
                'listByInvoiceIdForRepair',
                'updateForRepair',
                'maxInvoicedCycleIdForMembershipForRepair',
            ],
            'locked_generic_methods' => [
                'find',
                'findForUpdate',
                'update',
            ],
            'locked_mixed_methods' => [
                'findForInvoice',
                'findForUpdateForInvoice',
                'listByInvoiceId',
                'maxInvoicedCycleIdForMembership',
            ],
            'required_signals' => [
                'strictTenantInvoicePlaneBranchScope',
                'resolvedOrganizationRepairInvoicePlaneBranchScopeIfAvailable',
                'clientMembershipVisibleFromBranchContextClause',
            ],
        ],
        [
            'class' => 'PaymentRepository',
            'path' => 'sales/repositories/PaymentRepository.php',
            'required_runtime_methods' => [
                'findInInvoicePlane',
                'findForUpdateInInvoicePlane',
                'listByInvoiceIdInInvoicePlane',
                'getCompletedTotalByInvoiceIdInInvoicePlane',
                'existsCompletedByInvoiceAndReferenceInInvoicePlane',
                'getCompletedRefundedTotalForParentPaymentInInvoicePlane',
                'hasCompletedRefundForInvoiceInInvoicePlane',
            ],
            'required_non_runtime_methods' => [],
            'locked_generic_methods' => [
                'find',
                'findForUpdate',
            ],
            'locked_mixed_methods' => [
                'getByInvoiceId',
                'getCompletedTotalByInvoiceId',
                'existsCompletedByInvoiceAndReference',
                'getCompletedRefundedTotalForParentPayment',
                'hasCompletedRefundForInvoice',
            ],
            'required_signals' => [
                'requireBranchDerivedOrganizationIdForInvoicePlane',
                "paymentByInvoiceExistsClause('p', 'si')",
            ],
        ],
    ],
];
