<?php

declare(strict_types=1);

use Core\Middleware\AuthMiddleware;
use Core\Middleware\GuestMiddleware;
use Core\Middleware\PermissionMiddleware;

$router->get('/appointments', [\Modules\Appointments\Controllers\AppointmentController::class, 'index'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
$router->get('/appointments/slots', [\Modules\Appointments\Controllers\AppointmentController::class, 'slots'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
$router->get('/appointments/availability/staff/{id:\d+}', [\Modules\Appointments\Controllers\AppointmentController::class, 'staffAvailabilityAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
$router->get('/appointments/calendar/day', [\Modules\Appointments\Controllers\AppointmentController::class, 'dayCalendarPage'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
$router->get('/appointments/waitlist', [\Modules\Appointments\Controllers\AppointmentController::class, 'waitlistPage'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
$router->get('/appointments/waitlist/create', [\Modules\Appointments\Controllers\AppointmentController::class, 'waitlistCreate'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->post('/appointments/waitlist', [\Modules\Appointments\Controllers\AppointmentController::class, 'waitlistStore'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->post('/appointments/waitlist/{id:\d+}/status', [\Modules\Appointments\Controllers\AppointmentController::class, 'waitlistUpdateStatusAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/waitlist/{id:\d+}/link-appointment', [\Modules\Appointments\Controllers\AppointmentController::class, 'waitlistLinkAppointmentAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/waitlist/{id:\d+}/convert', [\Modules\Appointments\Controllers\AppointmentController::class, 'waitlistConvertAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->post('/appointments/series', [\Modules\Appointments\Controllers\AppointmentController::class, 'storeSeriesAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->post('/appointments/series/materialize', [\Modules\Appointments\Controllers\AppointmentController::class, 'seriesMaterializeAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->post('/appointments/series/cancel', [\Modules\Appointments\Controllers\AppointmentController::class, 'seriesCancelAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/series/occurrence/cancel', [\Modules\Appointments\Controllers\AppointmentController::class, 'seriesOccurrenceCancelAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/blocked-slots', [\Modules\Appointments\Controllers\AppointmentController::class, 'blockedSlotStore'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/blocked-slots/{id:\d+}/delete', [\Modules\Appointments\Controllers\AppointmentController::class, 'blockedSlotDelete'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->get('/appointments/create', [\Modules\Appointments\Controllers\AppointmentController::class, 'create'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->post('/appointments/create', [\Modules\Appointments\Controllers\AppointmentController::class, 'storeFromCreatePath'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->post('/appointments', [\Modules\Appointments\Controllers\AppointmentController::class, 'store'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.create')]);
$router->get('/appointments/{id:\d+}/print', [\Modules\Appointments\Controllers\AppointmentController::class, 'printSummaryPage'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
$router->get('/appointments/{id:\d+}/edit', [\Modules\Appointments\Controllers\AppointmentController::class, 'edit'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/{id:\d+}/cancel', [\Modules\Appointments\Controllers\AppointmentController::class, 'cancelAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/{id:\d+}/reschedule', [\Modules\Appointments\Controllers\AppointmentController::class, 'rescheduleAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/{id:\d+}/status', [\Modules\Appointments\Controllers\AppointmentController::class, 'updateStatusAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/{id:\d+}/check-in', [\Modules\Appointments\Controllers\AppointmentController::class, 'checkInAction'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->post('/appointments/{id:\d+}/consume-package', [\Modules\Appointments\Controllers\AppointmentController::class, 'consumePackage'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit'), \Core\Middleware\PermissionMiddleware::for('packages.use')]);
$router->post('/appointments/{id:\d+}/delete', [\Modules\Appointments\Controllers\AppointmentController::class, 'destroy'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.delete')]);
$router->get('/appointments/{id:\d+}', [\Modules\Appointments\Controllers\AppointmentController::class, 'show'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
$router->post('/appointments/{id:\d+}', [\Modules\Appointments\Controllers\AppointmentController::class, 'update'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.edit')]);
$router->get('/calendar/day', [\Modules\Appointments\Controllers\AppointmentController::class, 'dayCalendar'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('appointments.view')]);
