<?php

declare(strict_types=1);

use Core\Middleware\AuthMiddleware;
use Core\Middleware\GuestMiddleware;
use Core\Middleware\PermissionMiddleware;

$router->get('/marketing/campaigns', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'index'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.view')]);
$router->get('/marketing/campaigns/create', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'create'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/campaigns', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'store'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/campaigns/{id:\d+}', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'show'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.view')]);
$router->get('/marketing/campaigns/{id:\d+}/edit', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'edit'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/campaigns/{id:\d+}', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'update'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/campaigns/{id:\d+}/freeze-run', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'freezeRun'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/campaigns/runs/{runId:\d+}/recipients', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'runRecipients'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.view')]);
$router->post('/marketing/campaigns/runs/{runId:\d+}/dispatch', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'dispatchRun'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/campaigns/runs/{runId:\d+}/cancel', [\Modules\Marketing\Controllers\MarketingCampaignController::class, 'cancelRun'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/automations', [\Modules\Marketing\Controllers\MarketingAutomationController::class, 'index'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.view')]);
$router->post('/marketing/automations/scheduler-acknowledgment', [\Modules\Marketing\Controllers\MarketingAutomationController::class, 'saveSchedulerAcknowledgment'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/automations/{key:[a-z0-9_]+}/settings', [\Modules\Marketing\Controllers\MarketingAutomationController::class, 'saveSettings'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/automations/{key:[a-z0-9_]+}/toggle', [\Modules\Marketing\Controllers\MarketingAutomationController::class, 'toggle'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, \Core\Middleware\PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/contact-lists', [\Modules\Marketing\Controllers\MarketingContactListsController::class, 'index'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.view')]);
$router->get('/marketing/contact-lists/audience', [\Modules\Marketing\Controllers\MarketingContactListsController::class, 'audienceRead'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.view')]);
$router->post('/marketing/contact-lists/manual-lists/create', [\Modules\Marketing\Controllers\MarketingContactListsController::class, 'createManualList'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/contact-lists/manual-lists/rename', [\Modules\Marketing\Controllers\MarketingContactListsController::class, 'renameManualList'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/contact-lists/manual-lists/archive', [\Modules\Marketing\Controllers\MarketingContactListsController::class, 'archiveManualList'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/contact-lists/manual-lists/members/add', [\Modules\Marketing\Controllers\MarketingContactListsController::class, 'addContactsToList'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/contact-lists/manual-lists/members/remove', [\Modules\Marketing\Controllers\MarketingContactListsController::class, 'removeContactsFromList'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
// Special offers: admin CRUD only (H-006); not applied to booking/checkout/invoices until a pricing engine consumes this table.
$router->get('/marketing/promotions/special-offers', [\Modules\Marketing\Controllers\MarketingPromotionsController::class, 'specialOffers'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.view')]);
$router->post('/marketing/promotions/special-offers', [\Modules\Marketing\Controllers\MarketingPromotionsController::class, 'createSpecialOffer'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/promotions/special-offers/{id:\d+}/edit', [\Modules\Marketing\Controllers\MarketingPromotionsController::class, 'editSpecialOffer'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/promotions/special-offers/{id:\d+}', [\Modules\Marketing\Controllers\MarketingPromotionsController::class, 'updateSpecialOffer'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/promotions/special-offers/{id:\d+}/toggle-active', [\Modules\Marketing\Controllers\MarketingPromotionsController::class, 'toggleSpecialOfferActive'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/promotions/special-offers/{id:\d+}/delete', [\Modules\Marketing\Controllers\MarketingPromotionsController::class, 'deleteSpecialOffer'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/gift-card-templates', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'index'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.view')]);
$router->get('/marketing/gift-card-templates/create', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'create'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/gift-card-templates', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'store'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/gift-card-templates/{id:\d+}/edit', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'edit'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/gift-card-templates/{id:\d+}', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'update'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/gift-card-templates/{id:\d+}/archive', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'archive'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/gift-card-templates/images/status', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'imagesLibraryStatus'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->get('/marketing/gift-card-templates/images', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'images'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/gift-card-templates/images', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'uploadImage'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
$router->post('/marketing/gift-card-templates/images/{id:\d+}/delete', [\Modules\Marketing\Controllers\MarketingGiftCardTemplatesController::class, 'deleteImage'], [AuthMiddleware::class, \Core\Middleware\TenantProtectedRouteMiddleware::class, PermissionMiddleware::for('marketing.manage')]);
