<?php

declare(strict_types=1);

$container->singleton(\Modules\Appointments\Services\AppointmentService::class, fn ($c) => new \Modules\Appointments\Services\AppointmentService($c->get(\Modules\Appointments\Repositories\AppointmentRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Contracts\AppointmentPackageConsumptionProvider::class), $c->get(\Core\App\Database::class), $c->get(\Modules\Appointments\Services\AvailabilityService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Modules\Documents\Services\ConsentService::class), $c->get(\Core\App\SettingsService::class), $c->get(\Core\Permissions\PermissionService::class), $c->get(\Modules\Notifications\Services\NotificationService::class), $c->get(\Modules\Notifications\Services\OutboundTransactionalNotificationService::class), $c->get(\Modules\Memberships\Services\MembershipService::class), $c->get(\Modules\Staff\Services\StaffGroupService::class), $c->get(\Modules\ServicesResources\Services\ServiceStaffGroupEligibilityService::class), $c->get(\Modules\Settings\Services\BranchOperatingHoursService::class), $c->get(\Modules\Intake\Services\IntakeFormService::class), $c->get(\Core\Tenant\TenantOwnedDataScopeGuard::class), $c->get(\Modules\Settings\Services\AppointmentCancellationReasonService::class), $c->get(\Core\Branch\TenantBranchAccessService::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Appointments\Services\AppointmentSeriesService::class, fn ($c) => new \Modules\Appointments\Services\AppointmentSeriesService($c->get(\Modules\Appointments\Repositories\AppointmentSeriesRepository::class), $c->get(\Modules\Appointments\Services\AppointmentService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\App\Database::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Modules\Staff\Services\StaffGroupService::class), $c->get(\Modules\ServicesResources\Services\ServiceStaffGroupEligibilityService::class), $c->get(\Modules\Appointments\Services\AvailabilityService::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\OnlineBooking\Repositories\PublicBookingAbuseGuardRepository::class, fn ($c) => new \Modules\OnlineBooking\Repositories\PublicBookingAbuseGuardRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\OnlineBooking\Repositories\PublicBookingManageTokenRepository::class, fn ($c) => new \Modules\OnlineBooking\Repositories\PublicBookingManageTokenRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Core\Contracts\SlidingWindowRateLimiterInterface::class, function ($c) {
    $config = $c->get(\Core\App\Config::class);
    $url = trim((string) $config->get('app.redis_url', ''));
    $prefix = (string) $config->get('app.redis_key_prefix', 'spa');
    if ($url !== '' && extension_loaded('redis')) {
        try {
            $redis = \Core\Runtime\Redis\RedisFactory::connect($url);

            return new \Core\Runtime\RateLimit\RedisSlidingWindowRateLimiter($redis, $prefix);
        } catch (\Throwable) {
        }
    }

    return new \Core\Runtime\RateLimit\DatabaseSlidingWindowRateLimiter($c->get(\Modules\OnlineBooking\Repositories\PublicBookingAbuseGuardRepository::class));
});
$container->singleton(\Core\Runtime\RateLimit\RuntimeProtectedPathRateLimiter::class, fn ($c) => new \Core\Runtime\RateLimit\RuntimeProtectedPathRateLimiter(
    $c->get(\Core\Contracts\SlidingWindowRateLimiterInterface::class)
));
$container->singleton(\Modules\OnlineBooking\Services\PublicBookingAbuseGuardService::class, fn ($c) => new \Modules\OnlineBooking\Services\PublicBookingAbuseGuardService($c->get(\Core\Contracts\SlidingWindowRateLimiterInterface::class)));
$container->singleton(\Modules\OnlineBooking\Services\PublicBookingService::class, fn ($c) => new \Modules\OnlineBooking\Services\PublicBookingService($c->get(\Core\App\Database::class), $c->get(\Modules\Appointments\Services\AvailabilityService::class), $c->get(\Modules\Clients\Services\PublicClientResolutionService::class), $c->get(\Modules\Appointments\Services\AppointmentService::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\App\SettingsService::class), $c->get(\Modules\OnlineBooking\Repositories\PublicBookingManageTokenRepository::class), $c->get(\Core\Organization\OrganizationLifecycleGate::class), $c->get(\Modules\Settings\Services\AppointmentCancellationReasonService::class)));
$container->singleton(\Modules\OnlineBooking\Controllers\PublicBookingController::class, fn ($c) => new \Modules\OnlineBooking\Controllers\PublicBookingController($c->get(\Modules\OnlineBooking\Services\PublicBookingService::class), $c->get(\Modules\OnlineBooking\Services\PublicBookingAbuseGuardService::class), $c->get(\Core\Audit\AuditService::class)));
$container->singleton(\Modules\Appointments\Services\WaitlistService::class, fn ($c) => new \Modules\Appointments\Services\WaitlistService($c->get(\Modules\Appointments\Repositories\WaitlistRepository::class), $c->get(\Modules\Appointments\Repositories\AppointmentRepository::class), $c->get(\Modules\Appointments\Services\AppointmentService::class), $c->get(\Core\App\Database::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\App\SettingsService::class), $c->get(\Modules\Notifications\Services\NotificationService::class), $c->get(\Modules\Notifications\Services\OutboundTransactionalNotificationService::class), $c->get(\Modules\Appointments\Services\AvailabilityService::class), $c->get(\Core\Contracts\DistributedLockInterface::class)));
$container->singleton(\Modules\Appointments\Services\BlockedSlotService::class, fn ($c) => new \Modules\Appointments\Services\BlockedSlotService($c->get(\Modules\Appointments\Repositories\BlockedSlotRepository::class), $c->get(\Core\App\Database::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Modules\Appointments\Services\AvailabilityService::class)));
$container->singleton(\Core\Contracts\ClientAppointmentProfileProvider::class, fn ($c) => new \Modules\Appointments\Providers\ClientAppointmentProfileProviderImpl($c->get(\Core\App\Database::class), $c->get(\Modules\Clients\Services\ClientProfileAccessService::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class), $c->get(\Core\App\SettingsService::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\Appointments\Services\AppointmentPrintSummaryService::class, fn ($c) => new \Modules\Appointments\Services\AppointmentPrintSummaryService($c->get(\Modules\Appointments\Repositories\AppointmentRepository::class), $c->get(\Modules\Appointments\Services\AppointmentService::class), $c->get(\Modules\Clients\Services\ClientProfileAccessService::class), $c->get(\Core\Contracts\ClientAppointmentProfileProvider::class), $c->get(\Core\Contracts\AppointmentPackageConsumptionProvider::class), $c->get(\Core\Contracts\ClientPackageProfileProvider::class), $c->get(\Core\Contracts\ClientSalesProfileProvider::class), $c->get(\Core\App\SettingsService::class)));
$container->singleton(\Modules\Appointments\Controllers\AppointmentController::class, fn ($c) => new \Modules\Appointments\Controllers\AppointmentController($c->get(\Modules\Appointments\Repositories\AppointmentRepository::class), $c->get(\Modules\Appointments\Services\AppointmentService::class), $c->get(\Core\Contracts\ClientListProvider::class), $c->get(\Core\Contracts\ServiceListProvider::class), $c->get(\Core\Contracts\StaffListProvider::class), $c->get(\Core\Contracts\RoomListProvider::class), $c->get(\Core\Contracts\PackageAvailabilityProvider::class), $c->get(\Core\Contracts\AppointmentPackageConsumptionProvider::class), $c->get(\Modules\Appointments\Services\AvailabilityService::class), $c->get(\Modules\Appointments\Repositories\WaitlistRepository::class), $c->get(\Modules\Appointments\Services\WaitlistService::class), $c->get(\Modules\Appointments\Repositories\BlockedSlotRepository::class), $c->get(\Modules\Appointments\Services\BlockedSlotService::class), $c->get(\Modules\Appointments\Services\AppointmentSeriesService::class), $c->get(\Core\Branch\BranchDirectory::class), $c->get(\Modules\Settings\Services\BranchOperatingHoursService::class), $c->get(\Modules\Settings\Services\BranchClosureDateService::class), $c->get(\Core\App\SettingsService::class), $c->get(\Core\Contracts\ClientAppointmentProfileProvider::class), $c->get(\Modules\Appointments\Services\AppointmentPrintSummaryService::class), $c->get(\Core\Branch\TenantBranchAccessService::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Core\Contracts\AppointmentCheckoutProvider::class, fn ($c) => new \Modules\Appointments\Providers\AppointmentCheckoutProviderImpl($c->get(\Modules\Appointments\Repositories\AppointmentRepository::class), $c->get(\Core\Contracts\ServiceListProvider::class)));
