<?php

declare(strict_types=1);

$container->singleton(\Modules\Clients\Support\ClientNormalizedSearchSchemaReadiness::class, fn ($c) => new \Modules\Clients\Support\ClientNormalizedSearchSchemaReadiness($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Clients\Repositories\ClientRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Modules\Clients\Support\ClientNormalizedSearchSchemaReadiness::class)));
$container->singleton(\Modules\Clients\Services\ClientProfileAccessService::class, fn ($c) => new \Modules\Clients\Services\ClientProfileAccessService($c->get(\Core\Branch\BranchContext::class), $c->get(\Modules\Clients\Repositories\ClientRepository::class)));
$container->singleton(\Modules\Clients\Services\PublicClientResolutionService::class, fn ($c) => new \Modules\Clients\Services\PublicClientResolutionService($c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\App\SettingsService::class)));
$container->singleton(\Modules\Clients\Services\ClientInputValidator::class, fn () => new \Modules\Clients\Services\ClientInputValidator());
$container->singleton(\Modules\Clients\Repositories\ClientFieldDefinitionRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientFieldDefinitionRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Clients\Repositories\ClientFieldValueRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientFieldValueRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Clients\Services\ClientFieldCatalogService::class, fn () => new \Modules\Clients\Services\ClientFieldCatalogService());
$container->singleton(\Modules\Clients\Repositories\ClientPageLayoutProfileRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientPageLayoutProfileRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Clients\Repositories\ClientPageLayoutItemRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientPageLayoutItemRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Clients\Services\ClientPageLayoutService::class, fn ($c) => new \Modules\Clients\Services\ClientPageLayoutService(
    $c->get(\Core\Organization\OrganizationContext::class),
    $c->get(\Core\Tenant\TenantOwnedDataScopeGuard::class),
    $c->get(\Core\App\Database::class),
    $c->get(\Modules\Clients\Repositories\ClientPageLayoutProfileRepository::class),
    $c->get(\Modules\Clients\Repositories\ClientPageLayoutItemRepository::class),
    $c->get(\Modules\Clients\Services\ClientFieldCatalogService::class),
    $c->get(\Modules\Clients\Repositories\ClientFieldDefinitionRepository::class),
));
$container->singleton(\Modules\Clients\Repositories\ClientRegistrationRequestRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientRegistrationRequestRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Clients\Repositories\ClientIssueFlagRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientIssueFlagRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Clients\Repositories\ClientMergeJobRepository::class, fn ($c) => new \Modules\Clients\Repositories\ClientMergeJobRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Clients\Services\ClientService::class, fn ($c) => new \Modules\Clients\Services\ClientService($c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\App\Database::class), $c->get(\Modules\Clients\Repositories\ClientFieldDefinitionRepository::class), $c->get(\Modules\Clients\Repositories\ClientFieldValueRepository::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Core\Kernel\Authorization\AuthorizerInterface::class)));
$container->singleton(\Modules\Clients\Services\ClientMergeJobService::class, fn ($c) => new \Modules\Clients\Services\ClientMergeJobService($c->get(\Core\App\Database::class), $c->get(\Modules\Clients\Repositories\ClientMergeJobRepository::class), $c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Modules\Clients\Services\ClientService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Organization\OrganizationContext::class), $c->get(\Core\Organization\OutOfBandLifecycleGuard::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\Runtime\Queue\RuntimeAsyncJobRepository::class), $c->get(\Core\Kernel\Authorization\AuthorizerInterface::class)));
$container->singleton(\Modules\Clients\Services\ClientRegistrationService::class, fn ($c) => new \Modules\Clients\Services\ClientRegistrationService($c->get(\Modules\Clients\Repositories\ClientRegistrationRequestRepository::class), $c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Modules\Clients\Services\ClientService::class), $c->get(\Core\App\Database::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\App\SettingsService::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Core\Kernel\Authorization\AuthorizerInterface::class)));
$container->singleton(\Modules\Clients\Services\ClientIssueFlagService::class, fn ($c) => new \Modules\Clients\Services\ClientIssueFlagService($c->get(\Modules\Clients\Repositories\ClientIssueFlagRepository::class), $c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Core\App\Database::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Core\Kernel\Authorization\AuthorizerInterface::class)));
$container->singleton(\Modules\Clients\Services\ClientProfileReadService::class, fn ($c) => new \Modules\Clients\Services\ClientProfileReadService($c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Modules\Clients\Services\ClientService::class), $c->get(\Core\Contracts\ClientAppointmentProfileProvider::class), $c->get(\Core\Contracts\ClientSalesProfileProvider::class), $c->get(\Core\Contracts\ClientPackageProfileProvider::class), $c->get(\Core\Contracts\ClientGiftCardProfileProvider::class), $c->get(\Modules\Clients\Repositories\ClientIssueFlagRepository::class), $c->get(\Core\App\SettingsService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Modules\Clients\Services\ClientProfileImageService::class), $c->get(\Modules\Clients\Services\ClientPageLayoutService::class), $c->get(\Core\Permissions\PermissionService::class), $c->get(\Core\Auth\SessionAuth::class)));
$container->singleton(\Modules\Clients\Controllers\ClientController::class, fn ($c) => new \Modules\Clients\Controllers\ClientController($c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Modules\Clients\Services\ClientService::class), $c->get(\Core\Contracts\ClientAppointmentProfileProvider::class), $c->get(\Core\Contracts\ClientSalesProfileProvider::class), $c->get(\Core\Contracts\ClientPackageProfileProvider::class), $c->get(\Core\Contracts\ClientGiftCardProfileProvider::class), $c->get(\Modules\Clients\Repositories\ClientRegistrationRequestRepository::class), $c->get(\Modules\Clients\Services\ClientRegistrationService::class), $c->get(\Modules\Clients\Repositories\ClientIssueFlagRepository::class), $c->get(\Modules\Clients\Services\ClientIssueFlagService::class), $c->get(\Core\App\SettingsService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Branch\BranchDirectory::class), $c->get(\Modules\Clients\Services\ClientPageLayoutService::class), $c->get(\Modules\Clients\Services\ClientFieldCatalogService::class), $c->get(\Modules\Clients\Services\ClientInputValidator::class), $c->get(\Modules\Clients\Services\ClientProfileImageService::class), $c->get(\Modules\Clients\Services\ClientProfileReadService::class), $c->get(\Modules\Clients\Services\ClientMergeJobService::class)));
$container->singleton(\Core\Contracts\ClientListProvider::class, fn ($c) => new \Modules\Clients\Providers\ClientListProviderImpl($c->get(\Modules\Clients\Repositories\ClientRepository::class)));
