<?php

declare(strict_types=1);

$container->singleton(\Modules\Appointments\Repositories\AppointmentRepository::class, fn ($c) => new \Modules\Appointments\Repositories\AppointmentRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Appointments\Repositories\AppointmentSeriesRepository::class, fn ($c) => new \Modules\Appointments\Repositories\AppointmentSeriesRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Appointments\Repositories\WaitlistRepository::class, fn ($c) => new \Modules\Appointments\Repositories\WaitlistRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Appointments\Repositories\BlockedSlotRepository::class, fn ($c) => new \Modules\Appointments\Repositories\BlockedSlotRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Staff\Repositories\StaffAvailabilityExceptionRepository::class, fn ($c) => new \Modules\Staff\Repositories\StaffAvailabilityExceptionRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Appointments\Services\AvailabilityService::class, fn ($c) => new \Modules\Appointments\Services\AvailabilityService($c->get(\Core\App\Database::class), $c->get(\Modules\Appointments\Repositories\BlockedSlotRepository::class), $c->get(\Modules\Staff\Repositories\StaffScheduleRepository::class), $c->get(\Modules\Staff\Repositories\StaffBreakRepository::class), $c->get(\Modules\Staff\Repositories\StaffAvailabilityExceptionRepository::class), $c->get(\Modules\Staff\Services\StaffGroupService::class), $c->get(\Modules\ServicesResources\Services\ServiceStaffGroupEligibilityService::class), $c->get(\Modules\Settings\Services\BranchOperatingHoursService::class), $c->get(\Core\App\SettingsService::class), $c->get(\Modules\Appointments\Repositories\AppointmentRepository::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class), $c->get(\Core\Contracts\SharedCacheInterface::class)));
$container->singleton(\Modules\Documents\Repositories\DocumentDefinitionRepository::class, fn ($c) => new \Modules\Documents\Repositories\DocumentDefinitionRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Documents\Repositories\ClientConsentRepository::class, fn ($c) => new \Modules\Documents\Repositories\ClientConsentRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Documents\Repositories\DocumentRepository::class, fn ($c) => new \Modules\Documents\Repositories\DocumentRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Documents\Repositories\ServiceRequiredConsentRepository::class, fn ($c) => new \Modules\Documents\Repositories\ServiceRequiredConsentRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Documents\Services\ConsentService::class, fn ($c) => new \Modules\Documents\Services\ConsentService($c->get(\Modules\Documents\Repositories\DocumentDefinitionRepository::class), $c->get(\Modules\Documents\Repositories\ClientConsentRepository::class), $c->get(\Modules\Documents\Repositories\ServiceRequiredConsentRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Modules\Clients\Repositories\ClientRepository::class)));
$container->singleton(\Modules\Documents\Services\DocumentService::class, fn ($c) => new \Modules\Documents\Services\DocumentService($c->get(\Modules\Documents\Repositories\DocumentRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\App\Database::class), $c->get(\Core\Tenant\TenantOwnedDataScopeGuard::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class), $c->get(\Core\Storage\Contracts\StorageProviderInterface::class)));
$container->singleton(\Modules\Documents\Controllers\DocumentController::class, fn ($c) => new \Modules\Documents\Controllers\DocumentController($c->get(\Modules\Documents\Services\ConsentService::class), $c->get(\Modules\Documents\Services\DocumentService::class)));
$container->singleton(\Modules\Notifications\Repositories\NotificationRepository::class, fn ($c) => new \Modules\Notifications\Repositories\NotificationRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Notifications\Repositories\OutboundNotificationMessageRepository::class, fn ($c) => new \Modules\Notifications\Repositories\OutboundNotificationMessageRepository($c->get(\Core\App\Database::class), $c->get(\Core\Runtime\Queue\RuntimeAsyncJobRepository::class)));
$container->singleton(\Modules\Notifications\Repositories\OutboundNotificationAttemptRepository::class, fn ($c) => new \Modules\Notifications\Repositories\OutboundNotificationAttemptRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Notifications\Services\OutboundTemplateRenderer::class, fn () => new \Modules\Notifications\Services\OutboundTemplateRenderer());
$container->singleton(\Modules\Notifications\Transports\LogOutboundMailTransport::class, fn ($c) => new \Modules\Notifications\Transports\LogOutboundMailTransport($c->get(\Core\App\Config::class)));
$container->singleton(\Modules\Notifications\Transports\PhpMailOutboundTransport::class, fn () => new \Modules\Notifications\Transports\PhpMailOutboundTransport());
$container->singleton(\Modules\Notifications\Transports\SmtpOutboundMailTransport::class, fn ($c) => new \Modules\Notifications\Transports\SmtpOutboundMailTransport($c->get(\Core\App\Config::class)));
$container->singleton(\Modules\Notifications\Services\OutboundTransactionalNotificationService::class, fn ($c) => new \Modules\Notifications\Services\OutboundTransactionalNotificationService($c->get(\Modules\Notifications\Repositories\OutboundNotificationMessageRepository::class), $c->get(\Modules\Clients\Repositories\ClientRepository::class), $c->get(\Modules\Appointments\Repositories\AppointmentRepository::class), $c->get(\Core\App\SettingsService::class), $c->get(\Modules\Notifications\Services\OutboundTemplateRenderer::class)));
$container->singleton(\Modules\Notifications\Services\OutboundMarketingEnqueueService::class, fn ($c) => new \Modules\Notifications\Services\OutboundMarketingEnqueueService($c->get(\Modules\Notifications\Repositories\OutboundNotificationMessageRepository::class)));
$container->singleton(\Modules\Notifications\Services\OutboundNotificationDispatchService::class, fn ($c) => new \Modules\Notifications\Services\OutboundNotificationDispatchService($c->get(\Modules\Notifications\Repositories\OutboundNotificationMessageRepository::class), $c->get(\Modules\Notifications\Repositories\OutboundNotificationAttemptRepository::class), $c->get(\Core\App\Config::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Modules\Notifications\Transports\LogOutboundMailTransport::class), $c->get(\Modules\Notifications\Transports\PhpMailOutboundTransport::class), $c->get(\Modules\Notifications\Transports\SmtpOutboundMailTransport::class), $c->get(\Core\Organization\OutOfBandLifecycleGuard::class)));
$container->singleton(\Modules\Auth\Services\PasswordResetService::class, fn ($c) => new \Modules\Auth\Services\PasswordResetService($c->get(\Core\App\Database::class), $c->get(\Core\Auth\UserPasswordResetTokenRepository::class), $c->get(\Core\Auth\PasswordResetRequestLogRepository::class), $c->get(\Modules\Notifications\Repositories\OutboundNotificationMessageRepository::class), $c->get(\Core\Audit\AuditService::class)));
$container->singleton(\Modules\Notifications\Services\NotificationService::class, fn ($c) => new \Modules\Notifications\Services\NotificationService($c->get(\Modules\Notifications\Repositories\NotificationRepository::class), $c->get(\Core\App\SettingsService::class), $c->get(\Core\Audit\AuditService::class)));
$container->singleton(\Modules\Notifications\Controllers\NotificationController::class, fn ($c) => new \Modules\Notifications\Controllers\NotificationController($c->get(\Modules\Notifications\Services\NotificationService::class), $c->get(\Core\Branch\BranchContext::class)));

