<?php

declare(strict_types=1);

$container->singleton(\Modules\Staff\Repositories\StaffRepository::class, fn ($c) => new \Modules\Staff\Repositories\StaffRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Staff\Repositories\StaffGroupRepository::class, fn ($c) => new \Modules\Staff\Repositories\StaffGroupRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Staff\Repositories\StaffScheduleRepository::class, fn ($c) => new \Modules\Staff\Repositories\StaffScheduleRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Staff\Repositories\StaffBreakRepository::class, fn ($c) => new \Modules\Staff\Repositories\StaffBreakRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Staff\Services\StaffService::class, fn ($c) => new \Modules\Staff\Services\StaffService($c->get(\Modules\Staff\Repositories\StaffRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Tenant\TenantOwnedDataScopeGuard::class)));
$container->singleton(\Modules\Staff\Services\StaffGroupService::class, fn ($c) => new \Modules\Staff\Services\StaffGroupService($c->get(\Modules\Staff\Repositories\StaffGroupRepository::class), $c->get(\Modules\Staff\Repositories\StaffRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class), $c->get(\Core\Permissions\PermissionService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\Kernel\Authorization\AuthorizerInterface::class)));
$container->singleton(\Modules\Staff\Services\StaffGroupPermissionService::class, fn ($c) => new \Modules\Staff\Services\StaffGroupPermissionService($c->get(\Modules\Staff\Repositories\StaffGroupRepository::class), $c->get(\Core\Permissions\StaffGroupPermissionRepository::class), $c->get(\Core\App\Database::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Permissions\PermissionService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\Kernel\Authorization\AuthorizerInterface::class)));
$container->singleton(\Modules\Staff\Services\StaffScheduleService::class, fn ($c) => new \Modules\Staff\Services\StaffScheduleService($c->get(\Modules\Staff\Repositories\StaffScheduleRepository::class), $c->get(\Modules\Staff\Repositories\StaffRepository::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\Staff\Services\StaffBreakService::class, fn ($c) => new \Modules\Staff\Services\StaffBreakService($c->get(\Modules\Staff\Repositories\StaffBreakRepository::class), $c->get(\Modules\Staff\Repositories\StaffRepository::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\Staff\Controllers\StaffController::class, fn ($c) => new \Modules\Staff\Controllers\StaffController($c->get(\Modules\Staff\Repositories\StaffRepository::class), $c->get(\Modules\Staff\Services\StaffService::class), $c->get(\Modules\Staff\Repositories\StaffScheduleRepository::class), $c->get(\Modules\Staff\Repositories\StaffBreakRepository::class), $c->get(\Modules\Staff\Services\StaffScheduleService::class), $c->get(\Modules\Staff\Services\StaffBreakService::class), $c->get(\Modules\Media\Services\MediaAssetUploadService::class), $c->get(\Modules\Staff\Repositories\StaffGroupRepository::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class), $c->get(\Modules\ServicesResources\Repositories\ServiceRepository::class)));
$container->singleton(\Modules\Staff\Controllers\StaffGroupAdminController::class, fn ($c) => new \Modules\Staff\Controllers\StaffGroupAdminController($c->get(\Modules\Staff\Repositories\StaffGroupRepository::class), $c->get(\Modules\Staff\Services\StaffGroupService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Staff\Controllers\StaffGroupController::class, fn ($c) => new \Modules\Staff\Controllers\StaffGroupController($c->get(\Modules\Staff\Repositories\StaffGroupRepository::class), $c->get(\Modules\Staff\Services\StaffGroupService::class), $c->get(\Modules\Staff\Services\StaffGroupPermissionService::class)));
$container->singleton(\Core\Contracts\StaffListProvider::class, fn ($c) => new \Modules\Staff\Providers\StaffListProviderImpl($c->get(\Modules\Staff\Repositories\StaffRepository::class), $c->get(\Modules\Staff\Services\StaffGroupService::class)));

