<?php

declare(strict_types=1);

$container->singleton(\Modules\Payroll\Repositories\PayrollCompensationRuleRepository::class, fn ($c) => new \Modules\Payroll\Repositories\PayrollCompensationRuleRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Payroll\Repositories\PayrollRunRepository::class, fn ($c) => new \Modules\Payroll\Repositories\PayrollRunRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Payroll\Repositories\PayrollCommissionLineRepository::class, fn ($c) => new \Modules\Payroll\Repositories\PayrollCommissionLineRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Payroll\Services\PayrollService::class, fn ($c) => new \Modules\Payroll\Services\PayrollService($c->get(\Core\App\Database::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Organization\OrganizationContext::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Modules\Payroll\Repositories\PayrollRunRepository::class), $c->get(\Modules\Payroll\Repositories\PayrollCommissionLineRepository::class), $c->get(\Modules\Payroll\Repositories\PayrollCompensationRuleRepository::class), $c->get(\Modules\Sales\Services\SalesTenantScope::class)));
$container->singleton(\Modules\Payroll\Controllers\PayrollRuleController::class, fn ($c) => new \Modules\Payroll\Controllers\PayrollRuleController($c->get(\Modules\Payroll\Repositories\PayrollCompensationRuleRepository::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Organization\OrganizationContext::class), $c->get(\Core\Organization\OrganizationScopedBranchAssert::class), $c->get(\Core\Auth\AuthService::class), $c->get(\Core\Permissions\PermissionService::class)));
$container->singleton(\Modules\Payroll\Controllers\PayrollRunController::class, fn ($c) => new \Modules\Payroll\Controllers\PayrollRunController($c->get(\Modules\Payroll\Repositories\PayrollRunRepository::class), $c->get(\Modules\Payroll\Repositories\PayrollCommissionLineRepository::class), $c->get(\Modules\Payroll\Services\PayrollService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Auth\AuthService::class), $c->get(\Core\Permissions\PermissionService::class), $c->get(\Modules\Staff\Repositories\StaffRepository::class), $c->get(\Core\Branch\BranchDirectory::class)));

