<?php

declare(strict_types=1);

$container->singleton(\Modules\Packages\Repositories\PackageRepository::class, fn ($c) => new \Modules\Packages\Repositories\PackageRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Packages\Repositories\ClientPackageRepository::class, fn ($c) => new \Modules\Packages\Repositories\ClientPackageRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\Packages\Repositories\PackageUsageRepository::class, fn ($c) => new \Modules\Packages\Repositories\PackageUsageRepository($c->get(\Core\App\Database::class)));
$container->singleton(\Modules\Packages\Services\PackageService::class, fn ($c) => new \Modules\Packages\Services\PackageService($c->get(\Modules\Packages\Repositories\PackageRepository::class), $c->get(\Modules\Packages\Repositories\ClientPackageRepository::class), $c->get(\Modules\Packages\Repositories\PackageUsageRepository::class), $c->get(\Core\App\Database::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Modules\Clients\Repositories\ClientRepository::class)));
$container->singleton(\Core\Contracts\PackageAvailabilityProvider::class, fn ($c) => new \Modules\Packages\Providers\PackageAvailabilityProviderImpl($c->get(\Modules\Packages\Repositories\ClientPackageRepository::class), $c->get(\Modules\Packages\Services\PackageService::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Core\Contracts\AppointmentPackageConsumptionProvider::class, fn ($c) => new \Modules\Packages\Providers\AppointmentPackageConsumptionProviderImpl($c->get(\Modules\Packages\Services\PackageService::class), $c->get(\Modules\Packages\Repositories\PackageUsageRepository::class)));
$container->singleton(\Core\Contracts\ClientPackageProfileProvider::class, fn ($c) => new \Modules\Packages\Providers\ClientPackageProfileProviderImpl($c->get(\Modules\Clients\Services\ClientProfileAccessService::class), $c->get(\Modules\Packages\Repositories\ClientPackageRepository::class)));
$container->singleton(\Modules\Packages\Controllers\PackageDefinitionController::class, fn ($c) => new \Modules\Packages\Controllers\PackageDefinitionController($c->get(\Modules\Packages\Repositories\PackageRepository::class), $c->get(\Modules\Packages\Services\PackageService::class), $c->get(\Core\Branch\BranchDirectory::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\Packages\Controllers\ClientPackageController::class, fn ($c) => new \Modules\Packages\Controllers\ClientPackageController($c->get(\Modules\Packages\Repositories\ClientPackageRepository::class), $c->get(\Modules\Packages\Repositories\PackageRepository::class), $c->get(\Modules\Packages\Repositories\PackageUsageRepository::class), $c->get(\Modules\Packages\Services\PackageService::class), $c->get(\Core\Contracts\ClientListProvider::class), $c->get(\Core\Branch\BranchDirectory::class), $c->get(\Core\Branch\BranchContext::class)));

