<?php

declare(strict_types=1);

$container->singleton(\Modules\ServicesResources\Repositories\ServiceCategoryRepository::class, fn ($c) => new \Modules\ServicesResources\Repositories\ServiceCategoryRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\ServicesResources\Repositories\ServiceStaffGroupRepository::class, fn ($c) => new \Modules\ServicesResources\Repositories\ServiceStaffGroupRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\ServicesResources\Services\ServiceStaffGroupEligibilityService::class, fn ($c) => new \Modules\ServicesResources\Services\ServiceStaffGroupEligibilityService($c->get(\Modules\ServicesResources\Repositories\ServiceStaffGroupRepository::class)));
$container->singleton(\Modules\ServicesResources\Repositories\ServiceRepository::class, fn ($c) => new \Modules\ServicesResources\Repositories\ServiceRepository($c->get(\Core\App\Database::class), $c->get(\Modules\ServicesResources\Repositories\ServiceStaffGroupRepository::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\ServicesResources\Repositories\RoomRepository::class, fn ($c) => new \Modules\ServicesResources\Repositories\RoomRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\ServicesResources\Repositories\EquipmentRepository::class, fn ($c) => new \Modules\ServicesResources\Repositories\EquipmentRepository($c->get(\Core\App\Database::class), $c->get(\Core\Organization\OrganizationRepositoryScope::class)));
$container->singleton(\Modules\ServicesResources\Services\ServiceCategoryService::class, fn ($c) => new \Modules\ServicesResources\Services\ServiceCategoryService($c->get(\Modules\ServicesResources\Repositories\ServiceCategoryRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\ServicesResources\Services\ServiceService::class, fn ($c) => new \Modules\ServicesResources\Services\ServiceService($c->get(\Modules\ServicesResources\Repositories\ServiceRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class), $c->get(\Core\Tenant\TenantOwnedDataScopeGuard::class), $c->get(\Modules\Staff\Repositories\StaffGroupRepository::class), $c->get(\Modules\Sales\Services\VatRateService::class), $c->get(\Core\Kernel\RequestContextHolder::class), $c->get(\Core\Kernel\Authorization\AuthorizerInterface::class)));
$container->singleton(\Modules\ServicesResources\Services\RoomService::class, fn ($c) => new \Modules\ServicesResources\Services\RoomService($c->get(\Modules\ServicesResources\Repositories\RoomRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\ServicesResources\Services\EquipmentService::class, fn ($c) => new \Modules\ServicesResources\Services\EquipmentService($c->get(\Modules\ServicesResources\Repositories\EquipmentRepository::class), $c->get(\Core\Audit\AuditService::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\ServicesResources\Controllers\ServicesResourcesController::class, fn ($c) => new \Modules\ServicesResources\Controllers\ServicesResourcesController());
$container->singleton(\Modules\ServicesResources\Controllers\ServiceCategoryController::class, fn ($c) => new \Modules\ServicesResources\Controllers\ServiceCategoryController($c->get(\Modules\ServicesResources\Repositories\ServiceCategoryRepository::class), $c->get(\Modules\ServicesResources\Services\ServiceCategoryService::class)));
$container->singleton(\Modules\ServicesResources\Controllers\ServiceController::class, fn ($c) => new \Modules\ServicesResources\Controllers\ServiceController($c->get(\Modules\ServicesResources\Repositories\ServiceRepository::class), $c->get(\Modules\ServicesResources\Services\ServiceService::class), $c->get(\Modules\ServicesResources\Repositories\ServiceCategoryRepository::class), $c->get(\Core\Contracts\StaffListProvider::class), $c->get(\Modules\ServicesResources\Repositories\RoomRepository::class), $c->get(\Modules\ServicesResources\Repositories\EquipmentRepository::class), $c->get(\Modules\Sales\Services\VatRateService::class), $c->get(\Modules\Staff\Repositories\StaffGroupRepository::class), $c->get(\Core\Branch\BranchContext::class)));
$container->singleton(\Modules\ServicesResources\Controllers\RoomController::class, fn ($c) => new \Modules\ServicesResources\Controllers\RoomController($c->get(\Modules\ServicesResources\Repositories\RoomRepository::class), $c->get(\Modules\ServicesResources\Services\RoomService::class)));
$container->singleton(\Modules\ServicesResources\Controllers\EquipmentController::class, fn ($c) => new \Modules\ServicesResources\Controllers\EquipmentController($c->get(\Modules\ServicesResources\Repositories\EquipmentRepository::class), $c->get(\Modules\ServicesResources\Services\EquipmentService::class)));
$container->singleton(\Core\Contracts\ServiceListProvider::class, fn ($c) => new \Modules\ServicesResources\Providers\ServiceListProviderImpl($c->get(\Modules\ServicesResources\Repositories\ServiceRepository::class)));
$container->singleton(\Core\Contracts\RoomListProvider::class, fn ($c) => new \Modules\ServicesResources\Providers\RoomListProviderImpl($c->get(\Modules\ServicesResources\Repositories\RoomRepository::class)));

